### ISSUE TITLE
runGenes not found when locally building vignettes

### ISSUE THREAD

**Issue by dpshepherd** [AllenInstitute/mfishtools#3]
Hi,

When I download and attempt to build the project with vignettes,

```
# More slowly, but with the vignettes:
devtools::install_github("AllenInstitute/mfishtools", build_opts = c("--no-resave-data", "--no-manual"))
```
I run into the following error,

```
E  creating vignettes (23.9s)
   --- re-building 'inhibitory_marker_mapping.Rmd' using rmarkdown
   Warning in cor(mapDat[kpVar, ], medianDat[kpVar, ], use = use, method = method) :
     the standard deviation is zero
   --- finished re-building 'inhibitory_marker_mapping.Rmd'
   
   --- re-building 'inhibitory_marker_selection.Rmd' using rmarkdown
   Quitting from lines 94-111 (inhibitory_marker_selection.Rmd) 
   Error: processing vignette 'inhibitory_marker_selection.Rmd' failed with diagnostics:
   object 'runGenes' not found
   --- failed re-building 'inhibitory_marker_selection.Rmd'
   
   SUMMARY: processing the following file failed:
     'inhibitory_marker_selection.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
```

I am running R 3.6 64-bit with RStudio Build 1379 (f1ac3452) on Windows 10 64-bit.

Any suggestions on how to move forward and locally build the vignettes?

Thanks,
Doug

**Comment by jeremymiller** [comment]
Unfortunately, I am not able to reproduce this error as the vignettes build fine on my computer.  You could locally build the vignette by either (1) Downloading the Rmd and html files directly from vignette folder [here](https://github.com/AllenInstitute/mfishtools/blob/master/vignettes/) or (2) Downloading [this file](https://github.com/AllenInstitute/mfishtools/blob/master/vignettes/inhibitory_marker_selection.Rmd) and running the code from R studio.  This second step should either generate the html file in the vignette or crash in the same place as in creating the vignette, in which case we may get a better idea of what the problem is.  

I plan to release an updated version of `mfishtools` in the next couple of months that **hopefully** will solve this issue.  I'll leave this issue open for now in case others have the same problem.

(Sorry for the delay in this response.  I will try and be better about checking these issues more frequently.)

**Comment by jeremymiller** [comment]
@dpshepherd: It turns out there was an error in the function filterPanelGenes, which I have corrected.  You should now be able to build the vignettes properly (and also filter genes correctly!).  Let me know if you have any additional issues.
